ENG-3150 postgres-image
entando/entando-postgres pull request #3
Opened 2022-01-26 10:42 UTC by smolino

2022-01-29 07:44 UTC, w-caffiero-entando requested changes

2022-01-29 07:44 UTC, w-caffiero-entando commented on Dockerfile.centos8
> +RUN echo "listen_addresses='*'" >> /var/lib/pgsql/14/data/postgresql.conf
@smolino unify the"RUNS" in 2-3 commands, no need to create 7 different layers here

2022-01-29 07:44 UTC, w-caffiero-entando commented on Dockerfile.ubi8
> +RUN echo "listen_addresses='*'" >> /var/lib/pgsql/14/data/postgresql.conf
@smolino unify the"RUNS" in 2-3 commands, no need to create 7 different layers here

2022-01-29 09:04 UTC, w-caffiero-entando commented on Dockerfile.ubi8
> +         echo "host all  all    0.0.0.0/0  md5" >> //var/lib/pgsql/14/data/pg_hba.conf && \
@smolino double slash at the start of the path

2022-01-29 09:04 UTC, w-caffiero-entando commented on Dockerfile.centos8
> +         echo "host all  all    0.0.0.0/0  md5" >> //var/lib/pgsql/14/data/pg_hba.conf && \
@smolino double slash at the start of the path

2022-02-01 09:38 UTC, cecchisandrone commented on entando-project
> +ENTANDO_PRJ_VERSION=14.0.0-SNAPSHOT
this should reflect Postgres version, so I would say 14.1.0

2022-02-01 09:38 UTC, cecchisandrone commented on Dockerfile.centos8
> +FROM rockylinux:8.5
Rename dockerfile as well

2022-02-01 11:12 UTC, cecchisandrone commented on .env
> +POSTGRES_USER=
these should be the supported variables

POSTGRESQL_USER
POSTGRESQL_PASSWORD
POSTGRESQL_DATABASE
POSTGRESQL_ADMIN_PASSWORD

2022-02-04 11:50 UTC, cecchisandrone approved these changes

2022-02-04 16:56 UTC, w-caffiero-entando approved these changes

2022-02-04 17:10 UTC, merged